### ISSUE TITLE
Region selection is broken on systems with multiple monitors

### ISSUE THREAD

**Issue by robindegen** [stevenhoving/camstudio#24]
The screen gets squashed to the left (black bar on the right) and the selection doesn't work at all, probably due to mouse cursor positions not being correct.

![region select](https://user-images.githubusercontent.com/5236908/45281988-ed7b8c00-b4d9-11e8-9420-6e18a63afba8.png)

**Comment by stevenhoving** [comment]
Region selection is broken on system who have swapped the main display.

part 2:
the getcursorpos handles multiple monitors in a weird way:
\see https://social.msdn.microsoft.com/Forums/vstudio/en-US/34bd062d-2100-4925-bdfa-9f98b881e7dc/winapi-getcursorpos-returning-incorrect-pointers-with-multiple-monitors?forum=vcgeneral

- [ ] convert rectangle selection code to use normalized values.

**Comment by stevenhoving** [comment]
fixed
