### ISSUE TITLE
Mouse clicks (visualized with red/blue circles) in created video are not removed

### ISSUE THREAD

**Issue by rrampen** [stevenhoving/camstudio#31]
When a click is done the video show a red circle (for left click) and blue (for right click).
The expected behavior should be that the circle should be visible for a specified time and then it should be removed but in the video this is not what is observed.
What is seen is that clicks are done and the red circle does not disappear.

**Comment by stevenhoving** [comment]
Duplicate see #30

**Comment by stevenhoving** [comment]
fixed
