### ISSUE TITLE
Crash when using shortcuts to start/stop a recording

### ISSUE THREAD

**Issue by d4k0** [stevenhoving/camstudio#33]
When I want to start a recording by pressing F7, Camstudio exits without any message. If I use the GUI button (or the system tray icon), the recordings starts without a problem.

The same problem occurs when I want to stop a recording with F8. Only using the GUI button or the system tray icon works without a crash.

I tested version 3.0 Alpha 2 on Windows 10 1809 x64.

**Comment by stevenhoving** [comment]
@d4k0 could you please re-test alpha 4 release.

**Comment by d4k0** [comment]
Thanks, it works now!
