### ISSUE TITLE
Which version of Visual Studio should I use?

### ISSUE THREAD

**Issue by xgenem** [stevenhoving/camstudio#36]
So this is really not an issue. But I want to know which version of Visual Studio can I use to be able to work on this code? I want to know answers before I am going to test one. Cause maybe, you know, I don't want to spend $$ for a hobby project.

It will be really cool if anyone can answer me. Thanks!

**Comment by stevenhoving** [comment]
Hi, the awnser to your question is: Visual Studio 2017 (Community/Professional/Enterprise)
See: https://visualstudio.microsoft.com/downloads/

**Comment by xgenem** [comment]
Great! Thanks! :-)
