### ISSUE TITLE
The future for this CamStudio fork

### ISSUE THREAD

**Issue by hansfn** [stevenhoving/camstudio#44]
First of all: Thank you for creating this fork! As a happy user of CamStudio for many years, I have considered many times to create a fork - or to help in the development which seems to have [stalled completely](https://sourceforge.net/projects/camstudio/). It seems you have done a lot of good work already :-)

I have some questions that you hopefully have time to answer:

1. How motivated are you about this project? Are you considering the work mostly done, or are you interested in getting other people involved? In other words, is it an option to make this more official - to use "GitHub Team for Open Source" - to avoid the forks of forks problem ...
2. Did you contact [Nick](https://sourceforge.net/u/nickthegeek/profile/) - the person behind camstudio.org and the SF project - about taking over the project and the domain? I know Camstudio has a bad reputation because of the downloads from camstudio.org, and I just hate those "driver" ads, so I am unsure about Nick's motivation ... 
3. I assume your version 3 has nothing to do with the version 3 that was mentioned back in 2010 ;-)
4. If making this the official Camstudio is no option, have you considered rebranding it?
5. Did you look at the competition - ShareX and others - before starting the work on this fork? If so, I would like to know what made you spend time on Camstudio? I don't know ShareX, but to me it seems bloated - I need just a screen recorder.

Anyway, the biggest problem is that your fork is hard to find. After verifying that your fork is as great as it seems, I will edit the Wikipedia article - which is a start.

**Comment by stevenhoving** [comment]
Hi, thank you for showing interest in my little pet project.

> How motivated are you about this project? Are you considering the work mostly done, or are you interested in getting other people involved? In other words, is it an option to make this more official - to use "GitHub Team for Open Source" - to avoid the forks of forks problem ...

This is a pet project. I have very little time atm, when I do have time and energy I work on it. I don't consider the work done (see the issues). I am interested in pull requests (but not loads of them). I am not going to make this project an official thing. I don't have the time nor interest to do so.

> Did you contact Nick - the person behind camstudio.org and the SF project - about taking over the project and the domain? I know Camstudio has a bad reputation because of the downloads from camstudio.org, and I just hate those "driver" ads, so I am unsure about Nick's motivation ...

I am not interested in taking over his domain, nor to contact him. Like I describe in the readme, this is a personal fork.

> I assume your version 3 has nothing to do with the version 3 that was mentioned back in 2010 ;-)
Yup, version 3 has nothing to do with the so called C# rewrite from 2010.

> If making this the official Camstudio is no option, have you considered rebranding it?
Atm I am not interested in rebranding it. Maybe in the future when I have more time and can finish of a couple of pending features.

> Did you look at the competition - ShareX and others - before starting the work on this fork? If so, I would like to know what made you spend time on Camstudio? I don't know ShareX, but to me it seems bloated - I need just a screen recorder.

Nope, this is a pet project. And like you, I just needed a screen recorder.

> Anyway, the biggest problem is that your fork is hard to find. 

I don't mind being hard to find.

Lol, I see that all my answers start with 'this is a pet project'. I hope you don't mind :D

**Comment by hansfn** [comment]
Thx for the very clear answer. Personal fork doesn't have to mean pet project, but I get the idea. I will not try to persuade you to go more official.

I think it sad that your fork is hard to find since 1) the official website provides bad installers and 2) you have made an effort updating the software. I just think your work should benefit more users.

I'm closing this issue now :-)

PS! In case you run out of energy, [Captura](https://mathewsachin.github.io/Captura/) seems promising. I haven't tested it - will try your CamStudio and Captura during Easter.
