### ISSUE TITLE
Are these installers free of malware?

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [stevenhoving/camstudio#51]
Just verifying for a friend… CamStudio has had a history of using the infamous installcore malware. I just wanted to make sure it’s safe for them to install.

**Comment by stevenhoving** [comment]
@RetroSoftwareRepository yes, these are clean. But don't take my word for it, you can create an installer yourself. Just follow the instructions in de readme.

[edit] I now see that there are no instructions in the readme on how to create the installer. In short, make sure you have installed inno setup. Run bootstrap.cmd and then run deploy.cmd that will create an installer.
