### ISSUE TITLE
CamStudio crashes with option 'Region -> Select Screen'

### ISSUE THREAD

**Issue by Ic3Digg3r** [stevenhoving/camstudio#52]
Installed: CamStudio Recorder v2.7.4
Happens after selecting 1 of 3 Monitors/Screens.
No problems with other region options.

**Comment by stevenhoving** [comment]
It is unfortunately for you that I do not support old CamStudio versions. And to be honest, I dont even have time to support my own work on the CamStudio fork.

And this bug report is a duplicate #47
